version: "3.3"

services:
  mongo:
    container_name: go-mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=blackmarllbor0
      - MONGO_INITDB_ROOT_PASSWORD=funcConnect()
    ports:
      - "27017:27017"
