version: "3.3"

services:
  mongo:
    container_name: go-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_DADABASE: root
    ports:
      - "27017:27017"
    command:
      - mongod